# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

puts "Tilling Soil..."
Book.destroy_all

m1 = Book.create(title: "It Ends with Us", author: "Colleen Hoover", description: "In this “brave and heartbreaking novel that digs its claws into you and doesn’t let go, long after you’ve finished it” (Anna Todd, New York Times bestselling author) from the #1 New York Times bestselling author of All Your Perfects, a workaholic with a too-good-to-be-true romance can’t stop thinking about her first love.", amazon_url: "https://www.amazon.com/Ends-Us-Novel-Colleen-Hoover/dp/1501110365/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=1501110365&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/51qX2RGyhhL._SX320_BO1,204,203,200_.jpg")
m2 = Book.create(title: "Where the Crawdads Sing", author: 'Delia Owens', description: "", amazon_url: "https://www.amazon.com/Where-Crawdads-Sing-Delia-Owens/dp/0735219109/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=0735219109&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/51k-fjlkb8L._SX331_BO1,204,203,200_.jpg")
m3 = Book.create(title: "Atomic Habits", author: "James Clear", description: "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.", amazon_url: "https://www.amazon.com/Atomic-Habits-Proven-Build-Break/dp/0735211299/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=0735211299&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/51-uspgqWIL._SX329_BO1,204,203,200_.jpg")
m4 = Book.create(title: "The Body Keeps the Score", author: "Dr. Bresser van der Kolk", description: "In The Body Keeps the Score, Dr. Bresser van der Kolk uses recent scientific advances to show how trauma literally reshapes both body and brain, compromising sufferers’ capacities for pleasure, engagement, self-control, and trust.", amazon_url: "https://www.amazon.com/Body-Keeps-Score-Healing-Trauma/dp/0143127748/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=0143127748&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/41D3enj6JVS._SY291_BO1,204,203,200_QL40_FMwebp_.jpg")
m5 = Book.create(title: "The Silent Patient", author: "Alex Michaelides", description: "The Silent Patient is a shocking psychological thriller of a woman’s act of violence against her husband―and of the therapist obsessed with uncovering her motive.", amazon_url: "https://www.amazon.com/Silent-Patient-Alex-Michaelides/dp/125030170X/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=125030170X&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/41WppYGh1pL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg")
m6 = Book.create(title: "Fahrenheit 451", author: "Ray Bradbury", description: "Guy Montag is a fireman. His job is to destroy the most illegal of commodities, the printed book, along with the houses in which they are hidden. Montag never questions the destruction and ruin his actions produce, returning each day to his bland life and wife, Mildred, who spends all day with her television “family.” But when he meets an eccentric young neighbor, Clarisse, who introduces him to a past where people didn’t live in fear and to a present where one sees the world through the ideas in books instead of the mindless chatter of television, Montag begins to question everything he has ever known.", amazon_url: "https://www.amazon.com/Fahrenheit-451-Ray-Bradbury/dp/1451673310/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=1451673310&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/41qI9quGIdL._SX324_BO1,204,203,200_.jpg")
m7 = Book.create(title: "Fairy Tale", author: "Stephen King", description: "Legendary storyteller Stephen King goes into the deepest well of his imagination in this spellbinding novel about a seventeen-year-old boy who inherits the keys to a parallel world where good and evil are at war, and the stakes could not be higher—for that world or ours.", amazon_url: "https://www.amazon.com/Fairy-Tale-Stephen-King/dp/1668002175/ref=zg_sccl_2/137-4790049-1403832?pd_rd_w=DQ57p&content-id=amzn1.sym.193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_p=193afb92-0c19-4833-86f8-850b5ba40291&pf_rd_r=KSESNGWWMKTTDKP5X278&pd_rd_wg=X7yCN&pd_rd_r=7a63c7e6-5afb-4790-a2a1-814f5ceb3cb6&pd_rd_i=1668002175&psc=1", img_url: "https://images-na.ssl-images-amazon.com/images/I/51mDSB+k7YL._SX327_BO1,204,203,200_.jpg")
m8 = Book.create(title: "The Thicket", author: "Noelle West Ihli", description: "Norah ignored her brother's screams that night. Because nothing in the haunted attraction was supposed to be real—let alone deadly. Later, security footage will reveal that the killer walked right through the crowded plaza, his clothes stained red. Desperate for answers and tormented by survivor's guilt, Norah returns to the scene of the crime. And to her horror, the chorus of screams is louder than ever. Thrill seekers, including some of her classmates, are still eagerly lining up to purchase tickets. But the killer hasn’t chosen his hunting ground at random.", amazon_url: "https://www.amazon.com/dp/057894684X/ref=sspa_dk_detail_3?psc=1&pd_rd_i=057894684X&pd_rd_w=2m9Ad&content-id=amzn1.sym.3be1c5b9-5b41-4830-a902-fa8556c19eb5&pf_rd_p=3be1c5b9-5b41-4830-a902-fa8556c19eb5&pf_rd_r=8HHWG85BBCPYMG3H23VR&pd_rd_wg=B7td0&pd_rd_r=86afdd01-2d5d-45f1-803a-42cc8bba2f11&s=books&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyQlZKNzMxOENZVTM5JmVuY3J5cHRlZElkPUEwMjU1ODU0MVY5MlhSUlZNODlaSCZlbmNyeXB0ZWRBZElkPUEwMTM5ODQ3WEVRUUlHMjE1WVBLJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==", img_url: "https://images-na.ssl-images-amazon.com/images/I/41vhNn75aFL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg")
m9 = Book.create(title: "Slow Horses", author: "Mick Herron", description: "Welcome to the thrilling and unnervingly prescient world of the slow horses. This team of MI5 agents is united by one common bond: They've screwed up royally and will do anything to redeem themselves.", amazon_url: "https://www.amazon.com/dp/1641292970/ref=s9_acsd_al_bw_c2_x_1_i?pf_rd_m=ATVPDKIKX0DER&pf_rd_s=merchandised-search-14&pf_rd_r=37ET3R5FTCNRB7GY4091&pf_rd_t=101&pf_rd_p=481295f4-74f1-4b92-9ac2-eaff5e2824d9&pf_rd_i=283155", img_url: "https://images-na.ssl-images-amazon.com/images/I/51xT+Xll-VL._SY344_BO1,204,203,200_.jpg")
m10 = Book.create(title: "House of Mirth", author: "Edith Wharton", description: "The story of Lily Bart, a well-born woman belonging to New York City's high society around the end of the 19th century.", amazon_url: "https://www.amazon.com/House-Mirth-Edith-Wharton-ebook/dp/B0083ZABJ4?ref_=arp_L_abr_rwt_0000_prwgt_B0B9ZX9VSD", img_url: "https://m.media-amazon.com/images/I/41XfaSvSCJL.jpg")
m11 = Book.create(title: "Mike Nichols: A Life", author: "Mark Harris", description: "A magnificent biography of one of the most protean creative forces in American entertainment history, a life of dazzling highs and vertiginous plunges—some of the worst largely unknown until now—by the acclaimed author of Pictures at a Revolution and Five Came Back", amazon_url: "https://www.amazon.com/Mike-Nichols-Life-Mark-Harris-ebook/dp/B088QLXKXX?ref_=arp_L_abr_rwt_0000_prwgt_B0B9ZX9VSD", img_url: "https://m.media-amazon.com/images/I/41eRSAtDo6L.jpg")
m12 = Book.create(title: "The Lying Life of Adults", author: "Elena Ferrante", description: "A POWERFUL NEW NOVEL set in a divided Naples by ELENA FERRANTE, the New York Times best-selling author of My Brilliant Friend and The Lost Daughter. Soon to be a NETFLIX Original Series.", amazon_url: "https://www.amazon.com/Lying-Life-Adults-Elena-Ferrante-ebook/dp/B07ZPJ2BR5?ref_=arp_L_abr_rwt_0000_prwgt_B0B9ZX9VSD", img_url: "https://m.media-amazon.com/images/I/41oyD526-AL.jpg")
m13 = Book.create(title: "Giovanni's Room", author: "James Baldwin", description: "Set among the bohemian bars and nightclubs of 1950s Paris, this groundbreaking novel about love and the fear of love is `a book that belongs in the top rank of fiction` (The Atlantic).", amazon_url: "https://www.amazon.com/Giovannis-Vintage-International-James-Baldwin-ebook/dp/B00BABTC20?ref_=arp_L_abr_rwt_0000_prwgt_B0B9ZX9VSD", img_url: "https://m.media-amazon.com/images/I/41jVbUVBDVL.jpg")
m14 = Book.create(title: "Yes to Life", author: "Victor Frankl", description: "Eleven months after he was liberated from the Nazi concentration camps, Viktor E. Frankl held a series of public lectures in Vienna. The psychiatrist, who would soon become world famous, explained his central thoughts on meaning, resilience, and the importance of embracing life even in the face of great adversity.", amazon_url: "https://www.amazon.com/Yes-Life-Everything-Viktor-Frankl-ebook/dp/B07ZN343N6?ref_=arp_L_abr_rwt_0000_prwgt_B0B9HSGRCN", img_url: "https://m.media-amazon.com/images/I/51YTj-zXQ2L._SY346_.jpg")
m15 = Book.create(title: "Maybe You Never Cry Again", author: "Bernie Mac", description: "When young Bernie Mac lost his beloved mother to breast cancer, and faced an astounding number of other hardships, he remembered the “Mac-isms” she taught him: You have to meet all of the challenges, big and small. Because how you start is how you finish. If you want a helping hand, look at the end of your arm. These tough-love lessons gave him an inner strength that led him to choose hope over despair, and to follow his dreams. Maybe You Never Cry Again is a powerful testament to how a mother’s love made everything possible for Bernie Mac by teaching him to believe in himself.", amazon_url: "https://www.amazon.com/Maybe-You-Never-Cry-Again-ebook/dp/B001IG9D3K?ref_=arp_L_abr_rwt_0000_prwgt_B0B9HSGRCN", img_url: "https://m.media-amazon.com/images/I/51+dMVT1jZL.jpg")
m16 = Book.create(title: "All About Love", author: "Bell Hooks", description: "All About Love is the acclaimed first volume in feminist icon bell hooks' 1Love Song to the Nation`` trilogy.  All About Love reveals what causes a polarized society, and how to heal the divisions that cause suffering. Here is the truth about love, and inspiration to help us instill caring, compassion, and strength in our homes, schools, and workplaces.", amazon_url: "https://www.amazon.com/All-About-Love-Visions-Paperback-ebook/dp/B078GL796R?ref_=arp_L_abr_rwt_0000_prwgt_B0B5W39JKX", img_url: "https://m.media-amazon.com/images/I/41C2g-DTB1L.jpg")
m17 = Book.create(title: "Busy Being Free", author: "Emma Forrest", description: "No description available", amazon_url: "https://www.amazon.com/Busy-Being-Free-Lifelong-Romantic-ebook/dp/B09LLKKRGX?ref_=arp_L_abr_rwt_0000_prwgt_B0B5W39JKX", img_url: "https://m.media-amazon.com/images/I/41IPOjQxK0L.jpg")
m18 = Book.create(title: "Run Towards the Danger", author: "Sarah Polley", description: "Oscar-nominated screenwriter, director, and actor Sarah Polley’s Run Towards the Danger explores memory and the dialogue between her past and her present. In this extraordinary book, Polley explores what it is to live in one’s body, in a constant state of becoming, learning, and changing.", amazon_url: "https://www.amazon.com/Run-Towards-Danger-Confrontations-Memory-ebook/dp/B096DJY7Q4?ref_=arp_L_abr_rwt_0000_prwgt_B0B5W39JKX", img_url: "https://m.media-amazon.com/images/I/415ddwMUNjL.jpg")
m19 = Book.create(title: "Big Magic", author: "Elizabeth Gilbert", description: "Readers of all ages and walks of life have drawn inspiration and empowerment from Elizabeth Gilbert’s books for years. Now this beloved author digs deep into her own generative process to share her wisdom and unique perspective about creativity. With profound empathy and radiant generosity, she offers potent insights into the mysterious nature of inspiration. She asks us to embrace our curiosity and let go of needless suffering.", amazon_url: "https://www.amazon.com/Big-Magic-Creative-Living-Beyond-ebook/dp/B00S52M350?ref_=arp_L_abr_rwt_0000_prwgt_B0B5W39JKX", img_url: "https://m.media-amazon.com/images/I/51B12SO5RGL.jpg")
m20 = Book.create(title: "Elastic Habits", author: "Stephen Guise", description: "In this book, you’ll find a comprehensive framework of elasticity for habit building. Elastic materials are stronger than rigid, brittle materials because they can adapt to pressure. The same is true for habits. Any dread or sense of monotony you’ve felt about forming habits will disappear, because this system is dynamic and exciting.", amazon_url: "https://www.amazon.com/dp/B08188WBGC/ref=sspa_dk_detail_4?psc=1&pd_rd_i=B08188WBGC&pd_rd_w=8J0Jv&content-id=amzn1.sym.3be1c5b9-5b41-4830-a902-fa8556c19eb5&pf_rd_p=3be1c5b9-5b41-4830-a902-fa8556c19eb5&pf_rd_r=XEFMVZ21A6SK3MHCBK71&pd_rd_wg=fAoz9&pd_rd_r=b3b13df4-2906-42b9-b0b9-cc1cbe931d85&s=digital-text&sp_csd=d2lkZ2V0TmFtZT1zcF9kZXRhaWw&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUFUWVBTMlJSUTJMWUsmZW5jcnlwdGVkSWQ9QTAyNjA4MzczU1ZXWVJPUFhUUTQ0JmVuY3J5cHRlZEFkSWQ9QTA0NzAwNDQzVVU2RU1GVzQ3TlNCJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==", img_url: "https://m.media-amazon.com/images/I/41ZE3qJQHSL._SY346_.jpg")

